[phases.setup]
nixPkgs = ["nodejs", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-progress --no-interaction",
    "npm ci --prefer-offline --no-audit",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan cache:clear"
]

[start]
cmd = "chmod -R 775 storage bootstrap/cache && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
